//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="CParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface ICListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] CParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] CParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.preprocessorDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPreprocessorDirective([NotNull] CParser.PreprocessorDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.preprocessorDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPreprocessorDirective([NotNull] CParser.PreprocessorDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.defineDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefineDirective([NotNull] CParser.DefineDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.defineDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefineDirective([NotNull] CParser.DefineDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.mainFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMainFunction([NotNull] CParser.MainFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.mainFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMainFunction([NotNull] CParser.MainFunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration([NotNull] CParser.DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration([NotNull] CParser.DeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.functionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDeclaration([NotNull] CParser.FunctionDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.functionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDeclaration([NotNull] CParser.FunctionDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterList([NotNull] CParser.ParameterListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterList([NotNull] CParser.ParameterListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter([NotNull] CParser.ParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter([NotNull] CParser.ParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDeclaration([NotNull] CParser.VariableDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDeclaration([NotNull] CParser.VariableDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.variableDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDeclarator([NotNull] CParser.VariableDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.variableDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDeclarator([NotNull] CParser.VariableDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.structDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructDeclaration([NotNull] CParser.StructDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.structDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructDeclaration([NotNull] CParser.StructDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.structMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructMember([NotNull] CParser.StructMemberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.structMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructMember([NotNull] CParser.StructMemberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.unionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnionDeclaration([NotNull] CParser.UnionDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.unionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnionDeclaration([NotNull] CParser.UnionDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.unionMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnionMember([NotNull] CParser.UnionMemberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.unionMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnionMember([NotNull] CParser.UnionMemberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] CParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] CParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] CParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] CParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.expressionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressionStatement([NotNull] CParser.ExpressionStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.expressionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressionStatement([NotNull] CParser.ExpressionStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.printfStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrintfStatement([NotNull] CParser.PrintfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.printfStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrintfStatement([NotNull] CParser.PrintfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.scanfStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScanfStatement([NotNull] CParser.ScanfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.scanfStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScanfStatement([NotNull] CParser.ScanfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.blockStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockStatement([NotNull] CParser.BlockStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.blockStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockStatement([NotNull] CParser.BlockStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStatement([NotNull] CParser.IfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStatement([NotNull] CParser.IfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.switchStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchStatement([NotNull] CParser.SwitchStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.switchStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchStatement([NotNull] CParser.SwitchStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.caseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaseStatement([NotNull] CParser.CaseStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.caseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaseStatement([NotNull] CParser.CaseStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.defaultStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefaultStatement([NotNull] CParser.DefaultStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.defaultStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefaultStatement([NotNull] CParser.DefaultStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForStatement([NotNull] CParser.ForStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForStatement([NotNull] CParser.ForStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileStatement([NotNull] CParser.WhileStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileStatement([NotNull] CParser.WhileStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.doWhileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDoWhileStatement([NotNull] CParser.DoWhileStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.doWhileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDoWhileStatement([NotNull] CParser.DoWhileStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.chamadaStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChamadaStatement([NotNull] CParser.ChamadaStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.chamadaStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChamadaStatement([NotNull] CParser.ChamadaStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStatement([NotNull] CParser.ReturnStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStatement([NotNull] CParser.ReturnStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.pointerDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPointerDeclaration([NotNull] CParser.PointerDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.pointerDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPointerDeclaration([NotNull] CParser.PointerDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.ternaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTernaryExpression([NotNull] CParser.TernaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.ternaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTernaryExpression([NotNull] CParser.TernaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] CParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] CParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] CParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] CParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.assignmentExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentExpression([NotNull] CParser.AssignmentExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.assignmentExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentExpression([NotNull] CParser.AssignmentExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.logicalOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalOrExpression([NotNull] CParser.LogicalOrExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.logicalOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalOrExpression([NotNull] CParser.LogicalOrExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.logicalAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalAndExpression([NotNull] CParser.LogicalAndExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.logicalAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalAndExpression([NotNull] CParser.LogicalAndExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.equalityExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqualityExpression([NotNull] CParser.EqualityExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.equalityExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqualityExpression([NotNull] CParser.EqualityExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationalExpression([NotNull] CParser.RelationalExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationalExpression([NotNull] CParser.RelationalExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditiveExpression([NotNull] CParser.AdditiveExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditiveExpression([NotNull] CParser.AdditiveExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplicativeExpression([NotNull] CParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplicativeExpression([NotNull] CParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryExpression([NotNull] CParser.UnaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryExpression([NotNull] CParser.UnaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimaryExpression([NotNull] CParser.PrimaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimaryExpression([NotNull] CParser.PrimaryExpressionContext context);
}
